In [65]:
# DNN classifier using the in box tensorflow classifier

import numpy as np
import tensorflow as tf
import time
import glob
import time
tf.logging.set_verbosity(tf.logging.INFO)
def main():
    # get the data
    data_folder_path = "/Users/ssk4/Downloads/data_subimage/"
    files = glob.glob(data_folder_path + "*.npy")

    # shuffling the files to avoid any single dot bias
    import random
    random.shuffle(files)
    
    # downsample the input size for testing
    files = files

    n_samples = len(files)
    train_sample_ratio = 0.8
    n_train = int(train_sample_ratio * n_samples)

    print("Total number of samples :",n_samples)
    print("Training samples :",n_train)
    print("Test samples :",n_samples - n_train)
    
    
    feature_columns = [tf.contrib.layers.real_valued_column("",dimension=4)]
    
    classifier = tf.contrib.learn.DNNRegressor(feature_columns=feature_columns,
                                               hidden_units=[512,512,16],
                                               label_dimension=4,
                                               optimizer="Adam")
                                               
    
    def get_train_inputs():
        n_batch = 100
        index = np.random.choice(n_train,n_batch,replace=False)
        inp = []
        oup = []
        for i in index:
            dat = np.load(files[i])
            inp += [dat.item()['current_map'].flatten()]
            oup += [dat.item()['label']]

        inp = np.array(inp,dtype=np.float32)
        oup = np.array(oup,dtype=np.float32)

        x = tf.constant(inp)
        y = tf.constant(oup)
        return x,y
    
    # Fit the model. Magic happens here!
    classifier.fit(input_fn=get_train_inputs, steps=25000)
    
    def get_test_inputs():
        inp = []
        oup = []
        for file in files[n_train:]:
            dat = np.load(file)
            inp += [dat.item()['current_map'].flatten()]
            oup += [dat.item()['label']]

        inp = np.array(inp,dtype=np.float32)
        oup = np.array(oup,dtype=np.float32)

        x = tf.constant(inp)
        y = tf.constant(oup)
        return x,y
    
    accuracy_score = classifier.evaluate(input_fn=get_train_inputs,steps=1)["accuracy"]
    print("Train accuracy",accuracy_score)
    accuracy_score = classifier.evaluate(input_fn=get_test_inputs,steps=1)["accuracy"]
    print("Test accuracy",accuracy_score)
    
    return classifier
    
if __name__ == "__main__":
    st = time.time()
    classifier = main()
    print("Time",time.time()-st)

Total number of samples : 76700
Training samples : 61360
Test samples : 15340
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x11ec80cf8>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': None}
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer

KeyError: 'accuracy'

In [63]:
pred = classifier.predict_proba(input_fn=get_test_inputs,as_iterable=False)
print(pred)
print(out)

Instructions for updating:
The default behavior of predict() is changing. The default value for
as_iterable will change to True, and then the flag will be removed
altogether. The behavior of this flag is described below.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
INFO:tensorflow:Restoring parameters from /var/folders/hs/nm7qn85519v78y5bbl49h61h001sq3/T/tmpmrnnl258/model.ckpt-25000
[[  9.78449100e-10   1.07847231e-09   1.00000000e+00   1.57139624e-09]
 [  0.00000000e+00   1.26311873e-33   1.56145126e-19   1.00000000e+00]
 [  9.78449100e-10   1.07847231e-09   1.00000000e+00   1.57139624e-09]
 [  0.00000000e+00   1.60833024e-23   8.21347435e-11   1.00000000e+00]
 [  0.00000000e+00   8.10874685e-26   9.92522254e-13   1.00000000e+00]


In [64]:
# get the data
data_folder_path = "/Users/ssk4/Downloads/data_subimage/"
files = glob.glob(data_folder_path + "*.npy")

# shuffling the files to avoid any single dot bias
import random
random.shuffle(files)

# downsample the input size for testing
files = files[:1000]
n_samples = len(files)
train_sample_ratio = 0.8
n_train = int(train_sample_ratio * n_samples)

def get_test_inputs():
        inp = []
        oup = []
        for file in files[n_train:]:
            dat = np.load(file)
            inp += [dat.item()['current_map'].flatten()]
            oup += [dat.item()['label']]

        inp = np.array(inp,dtype=np.float32)
        oup = np.array(oup,dtype=np.float32)

        x = tf.constant(inp)
        y = tf.constant(oup)
        return x,y

In [29]:
pred

<generator object DNNClassifier.predict_classes.<locals>.<genexpr> at 0x11ea90eb8>

In [30]:
res = []
for i,p in enumerate(pred):
    res += [p]

In [31]:
res

[2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 2,
 3,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 2,
 2,
 3,
 3,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 3,
 2,
 2,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 3,
 2]

In [61]:
x,y = get_test_inputs()
sess = tf.Session()
out = sess.run(y)

In [36]:
import matplotlib.pyplot as plt
%matplotlib inline

diff = out- res

In [40]:
np.histogram(diff,[-1,0,1,2,3])

(array([ 16, 166,  18,   0]), array([-1,  0,  1,  2,  3]))

In [41]:
16 + 18

34

In [42]:
34/200

0.17